language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo test --verbose
  - cargo test --features use_optional --verbose
  - if [ "$TRAVIS_BRANCH" == "master" ]; then echo "Working on master branch" && cargo package --verbose; fi
